name: dart_cfstream
description: Dart bindings for CloudFlare Stream
version: 1.0.0
homepage: https://github.com/vidurb/dart-cfstream

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  universal_io: ^2.0.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
